"""
Schemas for Normalized External Disruption Information.

Defines standardized data models for weather hazards, port congestion,
traffic bottlenecks, and provider health states.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field


class DisruptionType(str, Enum):
    WEATHER = "WEATHER"
    PORT_CONGESTION = "PORT_CONGESTION"
    TRAFFIC = "TRAFFIC"
    CUSTOMS = "CUSTOMS"
    GEOPOLITICAL = "GEOPOLITICAL"
    INFRASTRUCTURE = "INFRASTRUCTURE"


class DisruptionSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ProviderStatus(str, Enum):
    HEALTHY = "HEALTHY"
    UNCONFIGURED = "UNCONFIGURED"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    MOCK_ACTIVE = "MOCK_ACTIVE"


class DisruptionLocation(BaseModel):
    name: str = Field(..., description="Hub or location identifier, e.g. 'Shanghai', 'Rotterdam'")
    city: Optional[str] = None
    country: Optional[str] = None
    region: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None


class NormalizedDisruptionEvent(BaseModel):
    """Unified schema representing a real or simulated disruption event across any provider."""

    event_id: str = Field(..., description="Unique event identifier")
    disruption_type: DisruptionType
    severity: DisruptionSeverity
    severity_score: float = Field(..., ge=0.0, le=100.0, description="Normalized risk index from 0 to 100")
    location: DisruptionLocation
    title: str = Field(..., description="Concise summary title of the disruption")
    description: str = Field(..., description="Detailed description of the operational impact")
    source_provider: str = Field(..., description="Originating provider/data source name")
    is_mock: bool = Field(default=False, description="True if generated by mock/local provider, False if live external API")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    valid_until: Optional[datetime] = None
    affected_radius_km: Optional[float] = None
    metrics: dict[str, Any] = Field(default_factory=dict, description="Domain-specific metrics (e.g. wind_speed, wait_days)")


class ProviderHealthResponse(BaseModel):
    """Health and connection status of an external disruption data provider."""

    provider_name: str
    provider_type: str
    status: ProviderStatus
    configured: bool
    is_mock: bool
    message: str
    last_checked: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DisruptionQueryRequest(BaseModel):
    location: Optional[str] = None
    disruption_type: Optional[DisruptionType] = None
    min_severity: Optional[DisruptionSeverity] = None
